// PLACEHOLDER DATA. Replaced by a call to /api/query once that endpoint exists.
//
// These rows satisfy the `Product` contract in shared/types.ts, so the swap is
// mechanical: drop this array, fetch the same shape.
//
// The 24 rows are read straight out of data/gold/dim_product.parquet (one or
// two per subcategory, spread across every category and brand), with the gold
// snake_case columns mapped onto the camelCase contract the same way /api/query
// will map them. Prices, weights, colours and product codes are the real values.
//
// One deliberate difference from the parquet: dimension values are trimmed here.
// data/gold/dim_product.parquet still carries trailing whitespace on 638 rows
// ("Cameras and camcorders ", "Litware "), which splits a facet in two. Until
// the ETL trims them, /api/query has to, or this UI does on read. The filter
// option lists below are derived from the data rather than hardcoded, so they
// stay correct either way.

import type { Product } from "@shared/types";

export type { Product };

export const SAMPLE_PRODUCTS: readonly Product[] = [
  {
    productKey: 111,
    productCode: "0106046",
    productName: "WWI Wireless Transmitter and Bluetooth Headphones X250 Black",
    brand: "Wide World Importers",
    manufacturer: "Wide World Importers",
    color: "Black",
    weight: 2.0,
    weightUnit: "pounds",
    price: 249.99,
    categoryName: "Audio",
    subCategoryName: "Bluetooth Headphones",
  },
  {
    productKey: 88,
    productCode: "0106023",
    productName: "NT Wireless Transmitter and Bluetooth Headphones M150 Black",
    brand: "Northwind Traders",
    manufacturer: "Northwind Traders",
    color: "Black",
    weight: 10.4,
    weightUnit: "ounces",
    price: 149.99,
    categoryName: "Audio",
    subCategoryName: "Bluetooth Headphones",
  },
  {
    productKey: 37,
    productCode: "0101037",
    productName: "Contoso 8GB Clock & Radio MP3 Player X850 Silver",
    brand: "Contoso",
    manufacturer: "Contoso, Ltd",
    color: "Silver",
    weight: 1.6,
    weightUnit: "ounces",
    price: 299.23,
    categoryName: "Audio",
    subCategoryName: "MP4&MP3",
  },
  {
    productKey: 1228,
    productCode: "0405085",
    productName: "Fabrikam Independent Filmmaker 1\" 25mm X400 Blue",
    brand: "Fabrikam",
    manufacturer: "Fabrikam, Inc.",
    color: "Blue",
    weight: 2.4,
    weightUnit: "pounds",
    price: 1620.0,
    categoryName: "Cameras and camcorders",
    subCategoryName: "Camcorders",
  },
  {
    productKey: 950,
    productCode: "0401007",
    productName: "A. Datum Super-zoom Digital Camera X300 Black",
    brand: "A. Datum",
    manufacturer: "A. Datum Corporation",
    color: "Black",
    weight: 4.7,
    weightUnit: "ounces",
    price: 290.0,
    categoryName: "Cameras and camcorders",
    subCategoryName: "Digital Cameras",
  },
  {
    productKey: 1088,
    productCode: "0402045",
    productName: "Contoso SLR Camera X144 Silver Grey",
    brand: "Contoso",
    manufacturer: "Contoso, Ltd",
    color: "Silver Grey",
    weight: 4.75,
    weightUnit: "pounds",
    price: 673.0,
    categoryName: "Cameras and camcorders",
    subCategoryName: "Digital SLR Cameras",
  },
  {
    productKey: 1409,
    productCode: "0503002",
    productName: "The Phone Company Touch Screen Phone 1600 TFT-1.4\" L250 Black",
    brand: "The Phone Company",
    manufacturer: "The Phone Company",
    color: "Black",
    weight: 6.0,
    weightUnit: "ounces",
    price: 589.0,
    categoryName: "Cell phones",
    subCategoryName: "Touch Screen Phones",
  },
  {
    productKey: 1525,
    productCode: "0504056",
    productName: "The Phone Company PDA Phone 4.7 inches L360 Black",
    brand: "The Phone Company",
    manufacturer: "The Phone Company",
    color: "Black",
    weight: 3.7,
    weightUnit: "ounces",
    price: 402.0,
    categoryName: "Cell phones",
    subCategoryName: "Smart phones & PDAs",
  },
  {
    productKey: 1328,
    productCode: "0501013",
    productName: "Contoso behind Centrex X15 Black",
    brand: "Contoso",
    manufacturer: "Contoso, Ltd",
    color: "Black",
    weight: 2.7,
    weightUnit: "pounds",
    price: 49.99,
    categoryName: "Cell phones",
    subCategoryName: "Home & Office Phones",
  },
  {
    productKey: 390,
    productCode: "0301053",
    productName: "WWI Laptop19W X0196 Black",
    brand: "Wide World Importers",
    manufacturer: "Wide World Importers",
    color: "Black",
    weight: 2.5,
    weightUnit: "pounds",
    price: 1299.0,
    categoryName: "Computers",
    subCategoryName: "Laptops",
  },
  {
    productKey: 462,
    productCode: "0304002",
    productName: "Proseware LCD24W X300 Black",
    brand: "Proseware",
    manufacturer: "Proseware, Inc.",
    color: "Black",
    weight: 10.8,
    weightUnit: "pounds",
    price: 869.0,
    categoryName: "Computers",
    subCategoryName: "Monitors",
  },
  {
    productKey: 663,
    productCode: "0306022",
    productName: "Proseware High-Performance Business-Class Laser Fax X200 Black",
    brand: "Proseware",
    manufacturer: "Proseware, Inc.",
    color: "Black",
    weight: 12.0,
    weightUnit: "pounds",
    price: 248.0,
    categoryName: "Computers",
    subCategoryName: "Printers, Scanners & Fax",
  },
  {
    productKey: 770,
    productCode: "0308028",
    productName: "Contoso ADSL Modem Splitter/Filter X 3 E300 Black",
    brand: "Contoso",
    manufacturer: "Contoso, Ltd",
    color: "Black",
    weight: 12.3,
    weightUnit: "pounds",
    price: 52.9,
    categoryName: "Computers",
    subCategoryName: "Computers Accessories",
  },
  {
    productKey: 1690,
    productCode: "0701030",
    productName: "SV Hand Games for Office worker L28 Yellow",
    brand: "Southridge Video",
    manufacturer: "Southridge Video",
    color: "Yellow",
    weight: 1.5,
    weightUnit: "pounds",
    price: 16.99,
    categoryName: "Games and Toys",
    subCategoryName: "Boxed Games",
  },
  {
    productKey: 1666,
    productCode: "0701006",
    productName: "MGS Hand Games for Office worker L299 Yellow",
    brand: "Tailspin Toys",
    manufacturer: "Tailspin Toys",
    color: "Yellow",
    weight: 1.0,
    weightUnit: "pounds",
    price: 16.89,
    categoryName: "Games and Toys",
    subCategoryName: "Boxed Games",
  },
  {
    productKey: 1939,
    productCode: "0802043",
    productName: "Litware Refrigerator 24.7CuFt X980 White",
    brand: "Litware",
    manufacturer: "Litware, Inc.",
    color: "White",
    weight: 175.0,
    weightUnit: "pounds",
    price: 3199.99,
    categoryName: "Home Appliances",
    subCategoryName: "Refrigerators",
  },
  {
    productKey: 1847,
    productCode: "0801021",
    productName: "NT Washer & Dryer 27in L2700 White",
    brand: "Northwind Traders",
    manufacturer: "Northwind Traders",
    color: "White",
    weight: 180.0,
    weightUnit: "pounds",
    price: 2652.9,
    categoryName: "Home Appliances",
    subCategoryName: "Washers & Dryers",
  },
  {
    productKey: 2140,
    productCode: "0805025",
    productName: "Adventure Works Coffee Maker Super-Auto 12C X125 Black",
    brand: "Adventure Works",
    manufacturer: "Adventure Works",
    color: "Black",
    weight: 26.0,
    weightUnit: "pounds",
    price: 1650.0,
    categoryName: "Home Appliances",
    subCategoryName: "Coffee Machines",
  },
  {
    productKey: 2085,
    productCode: "0804001",
    productName: "Contoso Water Heater 7.2GPM X1800 White",
    brand: "Contoso",
    manufacturer: "Contoso, Ltd",
    color: "White",
    weight: 22.0,
    weightUnit: "pounds",
    price: 1475.0,
    categoryName: "Home Appliances",
    subCategoryName: "Water Heaters",
  },
  {
    productKey: 2484,
    productCode: "0808075",
    productName: "Litware 18'' Oscillating Pedestal Fan M145 Pink",
    brand: "Litware",
    manufacturer: "Litware, Inc.",
    color: "Pink",
    weight: 2.0,
    weightUnit: "pounds",
    price: 400.0,
    categoryName: "Home Appliances",
    subCategoryName: "Fans",
  },
  {
    productKey: 1650,
    productCode: "0602080",
    productName: "Contoso DVD 15-Inch Player Portable L200 Black",
    brand: "Contoso",
    manufacturer: "Contoso, Ltd",
    color: "Black",
    weight: 48.0,
    weightUnit: "pounds",
    price: 289.99,
    categoryName: "Music, Movies and Audio Books",
    subCategoryName: "Movie DVD",
  },
  {
    productKey: 145,
    productCode: "0201030",
    productName: "Adventure Works 52\" LCD HDTV X590 Silver",
    brand: "Adventure Works",
    manufacturer: "Adventure Works",
    color: "Silver",
    weight: 22.5,
    weightUnit: "pounds",
    price: 2899.99,
    categoryName: "TV and Video",
    subCategoryName: "Televisions",
  },
  {
    productKey: 204,
    productCode: "0203013",
    productName: "Litware Home Theater System 7.1 Channel X711 Black",
    brand: "Litware",
    manufacturer: "Litware, Inc.",
    color: "Black",
    weight: 30.5,
    weightUnit: "pounds",
    price: 1109.0,
    categoryName: "TV and Video",
    subCategoryName: "Home Theater System",
  },
  {
    productKey: 172,
    productCode: "0202007",
    productName: "SV 22xDVD X680 Black",
    brand: "Southridge Video",
    manufacturer: "Southridge Video",
    color: "Black",
    weight: 6.2,
    weightUnit: "pounds",
    price: 169.0,
    categoryName: "TV and Video",
    subCategoryName: "VCD & DVD",
  },
];

/** Distinct category names, sorted. Derived, so it survives the API swap. */
export const CATEGORIES: readonly string[] = [
  ...new Set(SAMPLE_PRODUCTS.map((p) => p.categoryName)),
].sort();

/** Distinct brand names, sorted. Derived, so it survives the API swap. */
export const BRANDS: readonly string[] = [
  ...new Set(SAMPLE_PRODUCTS.map((p) => p.brand)),
].sort();

/**
 * Availability, derived from the product key.
 *
 * The `Product` contract carries no stock field and shared/types.ts is frozen,
 * so this stands in until the API can report real availability. Deterministic,
 * so a product does not change status between renders.
 */
export type Availability = "inStock" | "lowStock" | "madeToOrder";

export function availabilityOf(product: Product): Availability {
  const slot = product.productKey % 7;
  if (slot === 0) return "madeToOrder";
  if (slot === 1 || slot === 4) return "lowStock";
  return "inStock";
}
